name: CI

on: pull_request

env:
  NODE_VERSION: '21.4.0'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        width:
          node-version: NODE_VERSION

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  lint-styles:
    name: Lint styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: NODE_VERSION
      - name: Install dependencies
      - run: npm install
      - name: Run lint
      - run: npm run lint

    lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4